spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialize: true
    data: classpath:data.sql
    schema: classpath:schema.sql
  profiles:
    active: ${PROFILE_ACTIVE:dev}
    #active: pdn
#    url: jdbc:mysql://localhost:3306/hotel
#    username: root
#    password:
#  jpa:
#    hibernate.ddl-auto: none
#    generate-ddl: true
#    show-sql: true
