spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel2
    username: root
    password:
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
